In [1]:
import numpy as np

In [2]:
img = np.array([ [[1, 1, 1], [1, 1, 1], [1, 1, 1]], 
              [[1, 1, 1], [1, 1, 1], [1, 1, 1]], 
              [[1, 1, 1], [1, 1, 1], [1, 1, 1]] 
             ], np.int32)
img

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [3]:
filter_ = np.array([ [[1, 1], [1, 1]], 
                      [[1, 1], [1, 1]]
                    ], np.int32)
filter_

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [4]:
filtered_image = np.zeros(shape=[len(filter_),len(filter_[0]),len(filter_[0][0])], dtype=np.uint8)
filtered_image

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=uint8)

In [5]:
newX=0
newY=0
newZ =0
for i in range(len(img)-len(filter_)+1):
    for j in range(len(img[0])-len(filter_[0])+1):
        for k in range(len(img[0][0])-len(filter_[0][0])+1):
            sum_ = 0
            for x in range(len(filter_)):
                for y in range(len(filter_[0])):
                    for z in range(len(filter_[0][0])):
                        sum_ = sum_ + img[x+i, y+j, z+k]*filter_[x, y, z]         
            filtered_image[newX, newY, newZ] = sum_
            newZ = newZ + 1
        newY = newY + 1
        newZ = 0
    newX = newX + 1
    newY = 0
    newZ = 0
print(filtered_image)

[[[8 8]
  [8 8]]

 [[8 8]
  [8 8]]]
