In [3]:
import numpy as np

In [4]:
img = np.array([ [[1, 1, 1], [1, 1, 1], [1, 1, 1]], 
              [[1, 1, 1], [1, 1, 1], [1, 1, 1]], 
              [[1, 1, 1], [1, 1, 1], [1, 1, 1]] 
             ], np.int32)
img

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [5]:
filter_ = np.array([ [[1, 1], [1, 1]], 
                      [[1, 1], [1, 1]]
                    ], np.int32)
filter_

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [11]:
result = np.zeros(shape=[len(filter_),len(filter_[0]),len(filter_[0][0])], dtype=np.uint8)
result

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=uint8)

In [12]:
newX    = 0
newY    = 0
newZ    = 0
stribeX = 1
stribeY = 1
stribeZ = 1


for i in range(0, len(img)-len(filter_)+1, stribeX):
    for j in range(0, len(img[0])-len(filter_[0])+1, stribeY):
        for k in range(0, len(img[0][0])-len(filter_[0][0])+1, stribeZ):
            sum_ = 0
            for x in range(len(filter_)):
                for y in range(len(filter_[0])):
                    for z in range(len(filter_[0][0])):
                        sum_ = sum_ + img[x+i, y+j, z+k]*filter_[x, y, z]         
            result[newX, newY, newZ] = sum_
            newZ = newZ + 1
        newY = newY + 1
        newZ = 0
    newX = newX + 1
    newY = 0
    newZ = 0
print(result)

[[[8 8]
  [8 8]]

 [[8 8]
  [8 8]]]
